/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashish Shahi
 */
public class Database extends javax.swing.JInternalFrame {
         public static String x;
    /**
     * Creates new form JInternalFrame
     */
    public Database() {
        initComponents();
        x = "x";
        int a = Home.desktopPane.getWidth() - this.getWidth();
        int b = Home.desktopPane.getHeight() - this.getHeight();

        setLocation(a / 2, b / 2);
        setVisible(true);
    }
    //Define Variables
    String path = null;
    String filename;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Database = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        path_of_file = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        browsepath = new javax.swing.JButton();
        backup = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        message_for_restore = new javax.swing.JLabel();
        path_of_file_restore = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        browsepathrestore = new javax.swing.JButton();
        restore = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("DATABASE(Backup/Restore)");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/school/images/favicon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1186, 655));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Database.setPreferredSize(new java.awt.Dimension(1166, 583));

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane5.setForeground(new java.awt.Color(0, 39, 76));
        jTabbedPane5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTabbedPane5.setPreferredSize(new java.awt.Dimension(1146, 201));

        jPanel12.setBackground(new java.awt.Color(35, 46, 64));
        jPanel12.setPreferredSize(new java.awt.Dimension(1139, 145));

        path_of_file.setBackground(new java.awt.Color(35, 46, 64));
        path_of_file.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        path_of_file.setForeground(new java.awt.Color(255, 255, 255));
        path_of_file.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        path_of_file.setBorder(null);
        path_of_file.setCaretColor(new java.awt.Color(255, 255, 255));
        path_of_file.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        path_of_file.setEnabled(false);

        browsepath.setBackground(new java.awt.Color(0, 177, 176));
        browsepath.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        browsepath.setForeground(new java.awt.Color(255, 255, 255));
        browsepath.setText("BROWSE PATH");
        browsepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsepathActionPerformed(evt);
            }
        });

        backup.setBackground(new java.awt.Color(0, 177, 176));
        backup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backup.setForeground(new java.awt.Color(255, 255, 255));
        backup.setText("BACKUP");
        backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path_of_file, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(browsepath, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path_of_file, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browsepath, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("BACKUP DATABASE", jPanel12);

        jPanel13.setBackground(new java.awt.Color(35, 46, 64));
        jPanel13.setPreferredSize(new java.awt.Dimension(1139, 145));

        message_for_restore.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        message_for_restore.setForeground(new java.awt.Color(255, 255, 255));

        path_of_file_restore.setBackground(new java.awt.Color(35, 46, 64));
        path_of_file_restore.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        path_of_file_restore.setForeground(new java.awt.Color(255, 255, 255));
        path_of_file_restore.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        path_of_file_restore.setBorder(null);
        path_of_file_restore.setCaretColor(new java.awt.Color(255, 255, 255));
        path_of_file_restore.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        path_of_file_restore.setEnabled(false);

        browsepathrestore.setBackground(new java.awt.Color(0, 177, 176));
        browsepathrestore.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        browsepathrestore.setForeground(new java.awt.Color(255, 255, 255));
        browsepathrestore.setText("RESTORE PATH");
        browsepathrestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsepathrestoreActionPerformed(evt);
            }
        });

        restore.setBackground(new java.awt.Color(0, 177, 176));
        restore.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        restore.setForeground(new java.awt.Color(255, 255, 255));
        restore.setText("RESTORE");
        restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path_of_file_restore, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(message_for_restore, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(restore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(browsepathrestore, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path_of_file_restore, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browsepathrestore, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(restore, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(message_for_restore, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("RESTORE DATABASE", jPanel13);

        javax.swing.GroupLayout DatabaseLayout = new javax.swing.GroupLayout(Database);
        Database.setLayout(DatabaseLayout);
        DatabaseLayout.setHorizontalGroup(
            DatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatabaseLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        DatabaseLayout.setVerticalGroup(
            DatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatabaseLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(Database, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Database, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
         x = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void browsepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsepathActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        String date = new SimpleDateFormat("dd-MM-yyyy").format(new java.util.Date());
        try {
            File f = fc.getSelectedFile();
            path = f.getAbsolutePath();
            path = path.replace('\\', '/');
            path = path + "_" + date + ".sql";
            path_of_file.setText(path);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_browsepathActionPerformed

    private void backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupActionPerformed
        Process p =null;
        try {
            Runtime runtime = Runtime.getRuntime();
            p=runtime.exec("C:/xampp/mysql/bin/mysqldump.exe -uroot -p --add-drop-database -B test -r"+path);//-uroot -p1234 u means username and p means password.
            int processComplete = p.waitFor();
            if(processComplete == 0){
                message.setText("Bacup Create Sucessfully");
            }else{
                message.setText("Can't Create Backup");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_backupActionPerformed

    private void browsepathrestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsepathrestoreActionPerformed
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        try {
            File f = file.getSelectedFile();
            path = f.getAbsolutePath();
            path = path.replace("\\","/");
                path_of_file_restore.setText(path);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }//GEN-LAST:event_browsepathrestoreActionPerformed

    private void restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreActionPerformed
        String user = "root";
        String pass = "";
        String[] restoreCmd = new String[]{"C:/xampp/mysql/bin/mysql.exe","--user=" + user, "--password=" + pass, "-e", "source " + path};
        Process runtimProcess;
        try {
            runtimProcess = Runtime.getRuntime().exec(restoreCmd);
            int proceCom = runtimProcess.waitFor();

            if (proceCom==0) {
                message_for_restore.setText("Bacup Create Sucessfully .");
            }else{
                message_for_restore.setText("Can't Create Backup .");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_restoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Database;
    private javax.swing.JButton backup;
    private javax.swing.JButton browsepath;
    private javax.swing.JButton browsepathrestore;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel message;
    private javax.swing.JLabel message_for_restore;
    private javax.swing.JTextField path_of_file;
    private javax.swing.JTextField path_of_file_restore;
    private javax.swing.JButton restore;
    // End of variables declaration//GEN-END:variables
}
