/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static school.Users.x;

/**
 *
 * @author Ashish Shahi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
        this.setIconImage(new ImageIcon(getClass().getResource("/school/images/favicon.png")).getImage());
    }
   static boolean maximizer = true;
    static ImageIcon ii;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        maximize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        mainmenu = new javax.swing.JPanel();
        administrator = new javax.swing.JButton();
        students = new javax.swing.JButton();
        attendence = new javax.swing.JButton();
        employess = new javax.swing.JButton();
        accounts = new javax.swing.JButton();
        transport = new javax.swing.JButton();
        inventory = new javax.swing.JButton();
        report = new javax.swing.JButton();
        firstsub_menu = new javax.swing.JPanel();
        academic_year = new javax.swing.JButton();
        users = new javax.swing.JButton();
        standard_section = new javax.swing.JButton();
        branch = new javax.swing.JButton();
        backup_database = new javax.swing.JButton();
        secondsub_menu = new javax.swing.JPanel();
        RegButton = new javax.swing.JButton();
        BonafiedCerti = new javax.swing.JButton();
        StudentPromo = new javax.swing.JButton();
        thirdsub_menu = new javax.swing.JPanel();
        student_attandance = new javax.swing.JButton();
        employee_attandance = new javax.swing.JButton();
        fourthsub_menu = new javax.swing.JPanel();
        employee_registration = new javax.swing.JButton();
        fifthsub_menu = new javax.swing.JPanel();
        exp_type = new javax.swing.JButton();
        fee_stracture = new javax.swing.JButton();
        student_discount = new javax.swing.JButton();
        student_fees = new javax.swing.JButton();
        parent_communities = new javax.swing.JButton();
        due_fees = new javax.swing.JButton();
        sixthsub_menu = new javax.swing.JPanel();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        seventhsub_menu = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        eightsub_menu = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(3267, 44));

        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/images/mini.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        maximize.setForeground(new java.awt.Color(255, 255, 255));
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/images/maximize.png"))); // NOI18N
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("School Management System");

        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/images/cancel.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 795, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(maximize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(maximize)
                                .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainmenu.setBackground(new java.awt.Color(0, 39, 76));
        mainmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        administrator.setBackground(new java.awt.Color(0, 39, 76));
        administrator.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        administrator.setForeground(new java.awt.Color(255, 255, 255));
        administrator.setText("ADMINISTRATOR");
        administrator.setBorder(null);
        administrator.setBorderPainted(false);
        administrator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                administratorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                administratorMouseExited(evt);
            }
        });

        students.setBackground(new java.awt.Color(0, 39, 76));
        students.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        students.setForeground(new java.awt.Color(255, 255, 255));
        students.setText("STUDENTS");
        students.setBorder(null);
        students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentsMouseExited(evt);
            }
        });

        attendence.setBackground(new java.awt.Color(0, 39, 76));
        attendence.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        attendence.setForeground(new java.awt.Color(255, 255, 255));
        attendence.setText("ATTENDANCE");
        attendence.setBorder(null);
        attendence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                attendenceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendenceMouseExited(evt);
            }
        });

        employess.setBackground(new java.awt.Color(0, 39, 76));
        employess.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        employess.setForeground(new java.awt.Color(255, 255, 255));
        employess.setText("EMPLOYESS");
        employess.setBorder(null);
        employess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employessMouseExited(evt);
            }
        });

        accounts.setBackground(new java.awt.Color(0, 39, 76));
        accounts.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        accounts.setForeground(new java.awt.Color(255, 255, 255));
        accounts.setText("ACCOUNTS");
        accounts.setBorder(null);
        accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountsMouseExited(evt);
            }
        });

        transport.setBackground(new java.awt.Color(0, 39, 76));
        transport.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        transport.setForeground(new java.awt.Color(255, 255, 255));
        transport.setText("TRANSPORT");
        transport.setBorder(null);
        transport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transportMouseExited(evt);
            }
        });

        inventory.setBackground(new java.awt.Color(0, 39, 76));
        inventory.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inventory.setForeground(new java.awt.Color(255, 255, 255));
        inventory.setText("INVENTORY");
        inventory.setBorder(null);
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryMouseExited(evt);
            }
        });

        report.setBackground(new java.awt.Color(0, 39, 76));
        report.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("REPORT");
        report.setBorder(null);
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout mainmenuLayout = new javax.swing.GroupLayout(mainmenu);
        mainmenu.setLayout(mainmenuLayout);
        mainmenuLayout.setHorizontalGroup(
            mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(administrator, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(students, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(attendence, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employess, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accounts, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transport, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainmenuLayout.setVerticalGroup(
            mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainmenuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(mainmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accounts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(students, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(administrator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        firstsub_menu.setBackground(new java.awt.Color(0, 39, 76));
        firstsub_menu.setForeground(new java.awt.Color(255, 255, 255));
        firstsub_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        firstsub_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        academic_year.setBackground(new java.awt.Color(15, 108, 182));
        academic_year.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        academic_year.setForeground(new java.awt.Color(255, 255, 255));
        academic_year.setText("ACADEMIC YEAR");
        academic_year.setBorder(null);
        academic_year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        academic_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academic_yearActionPerformed(evt);
            }
        });

        users.setBackground(new java.awt.Color(15, 108, 182));
        users.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setText("USERS");
        users.setBorder(null);
        users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });

        standard_section.setBackground(new java.awt.Color(15, 108, 182));
        standard_section.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        standard_section.setForeground(new java.awt.Color(255, 255, 255));
        standard_section.setText("STANDARD SECTION");
        standard_section.setBorder(null);
        standard_section.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        standard_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standard_sectionActionPerformed(evt);
            }
        });

        branch.setBackground(new java.awt.Color(15, 108, 182));
        branch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        branch.setForeground(new java.awt.Color(255, 255, 255));
        branch.setText("BRANCH");
        branch.setBorder(null);
        branch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchActionPerformed(evt);
            }
        });

        backup_database.setBackground(new java.awt.Color(15, 108, 182));
        backup_database.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        backup_database.setForeground(new java.awt.Color(255, 255, 255));
        backup_database.setText("DATABASE");
        backup_database.setBorder(null);
        backup_database.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backup_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backup_databaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstsub_menuLayout = new javax.swing.GroupLayout(firstsub_menu);
        firstsub_menu.setLayout(firstsub_menuLayout);
        firstsub_menuLayout.setHorizontalGroup(
            firstsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(firstsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(academic_year, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(users, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standard_section, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backup_database, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
        firstsub_menuLayout.setVerticalGroup(
            firstsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(academic_year, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(standard_section, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backup_database, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        secondsub_menu.setBackground(new java.awt.Color(0, 39, 76));
        secondsub_menu.setForeground(new java.awt.Color(255, 255, 255));
        secondsub_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondsub_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        RegButton.setBackground(new java.awt.Color(15, 108, 182));
        RegButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RegButton.setForeground(new java.awt.Color(255, 255, 255));
        RegButton.setText("REGISTRATION");
        RegButton.setBorder(null);
        RegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButtonActionPerformed(evt);
            }
        });

        BonafiedCerti.setBackground(new java.awt.Color(15, 108, 182));
        BonafiedCerti.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BonafiedCerti.setForeground(new java.awt.Color(255, 255, 255));
        BonafiedCerti.setText("BONAFIED CERTIFICATE");
        BonafiedCerti.setBorder(null);
        BonafiedCerti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BonafiedCertiActionPerformed(evt);
            }
        });

        StudentPromo.setBackground(new java.awt.Color(15, 108, 182));
        StudentPromo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        StudentPromo.setForeground(new java.awt.Color(255, 255, 255));
        StudentPromo.setText("STUDENT PROMOTIONS");
        StudentPromo.setBorder(null);
        StudentPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPromoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secondsub_menuLayout = new javax.swing.GroupLayout(secondsub_menu);
        secondsub_menu.setLayout(secondsub_menuLayout);
        secondsub_menuLayout.setHorizontalGroup(
            secondsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(secondsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BonafiedCerti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentPromo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
        secondsub_menuLayout.setVerticalGroup(
            secondsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(RegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BonafiedCerti, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        thirdsub_menu.setBackground(new java.awt.Color(0, 39, 76));
        thirdsub_menu.setForeground(new java.awt.Color(255, 255, 255));
        thirdsub_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        thirdsub_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        student_attandance.setBackground(new java.awt.Color(15, 108, 182));
        student_attandance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        student_attandance.setForeground(new java.awt.Color(255, 255, 255));
        student_attandance.setText("STUDENT ATTENDENCE");
        student_attandance.setBorder(null);
        student_attandance.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        student_attandance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        student_attandance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_attandanceActionPerformed(evt);
            }
        });

        employee_attandance.setBackground(new java.awt.Color(15, 108, 182));
        employee_attandance.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        employee_attandance.setForeground(new java.awt.Color(255, 255, 255));
        employee_attandance.setText("EMPLOYEE ATTENDENCE");
        employee_attandance.setBorder(null);
        employee_attandance.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        employee_attandance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_attandanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout thirdsub_menuLayout = new javax.swing.GroupLayout(thirdsub_menu);
        thirdsub_menu.setLayout(thirdsub_menuLayout);
        thirdsub_menuLayout.setHorizontalGroup(
            thirdsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(thirdsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(student_attandance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employee_attandance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
        thirdsub_menuLayout.setVerticalGroup(
            thirdsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(student_attandance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employee_attandance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        fourthsub_menu.setBackground(new java.awt.Color(0, 39, 76));
        fourthsub_menu.setForeground(new java.awt.Color(255, 255, 255));
        fourthsub_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fourthsub_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        employee_registration.setBackground(new java.awt.Color(15, 108, 182));
        employee_registration.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        employee_registration.setForeground(new java.awt.Color(255, 255, 255));
        employee_registration.setText("EMPLOYEE REGISTRATION");
        employee_registration.setBorder(null);
        employee_registration.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employee_registration.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        employee_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_registrationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fourthsub_menuLayout = new javax.swing.GroupLayout(fourthsub_menu);
        fourthsub_menu.setLayout(fourthsub_menuLayout);
        fourthsub_menuLayout.setHorizontalGroup(
            fourthsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fourthsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(employee_registration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        fourthsub_menuLayout.setVerticalGroup(
            fourthsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fourthsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(employee_registration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        fifthsub_menu.setBackground(new java.awt.Color(0, 39, 76));
        fifthsub_menu.setForeground(new java.awt.Color(255, 255, 255));
        fifthsub_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fifthsub_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        exp_type.setBackground(new java.awt.Color(15, 108, 182));
        exp_type.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exp_type.setForeground(new java.awt.Color(255, 255, 255));
        exp_type.setText("EXPENSE TYPE AND PAYMENTS");
        exp_type.setBorder(null);
        exp_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exp_typeActionPerformed(evt);
            }
        });

        fee_stracture.setBackground(new java.awt.Color(15, 108, 182));
        fee_stracture.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fee_stracture.setForeground(new java.awt.Color(255, 255, 255));
        fee_stracture.setText("FEE STRACTURE AND SETUP");
        fee_stracture.setBorder(null);
        fee_stracture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fee_stractureActionPerformed(evt);
            }
        });

        student_discount.setBackground(new java.awt.Color(15, 108, 182));
        student_discount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        student_discount.setForeground(new java.awt.Color(255, 255, 255));
        student_discount.setText("STUDENT DISCOUNT");
        student_discount.setBorder(null);
        student_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_discountActionPerformed(evt);
            }
        });

        student_fees.setBackground(new java.awt.Color(15, 108, 182));
        student_fees.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        student_fees.setForeground(new java.awt.Color(255, 255, 255));
        student_fees.setText("STUDENT FEES");
        student_fees.setBorder(null);
        student_fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_feesActionPerformed(evt);
            }
        });

        parent_communities.setBackground(new java.awt.Color(15, 108, 182));
        parent_communities.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        parent_communities.setForeground(new java.awt.Color(255, 255, 255));
        parent_communities.setText("PARENT COMMUNITIES");
        parent_communities.setBorder(null);

        due_fees.setBackground(new java.awt.Color(15, 108, 182));
        due_fees.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        due_fees.setForeground(new java.awt.Color(255, 255, 255));
        due_fees.setText("DUE FEE");
        due_fees.setBorder(null);

        javax.swing.GroupLayout fifthsub_menuLayout = new javax.swing.GroupLayout(fifthsub_menu);
        fifthsub_menu.setLayout(fifthsub_menuLayout);
        fifthsub_menuLayout.setHorizontalGroup(
            fifthsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fifthsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(fifthsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(exp_type, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(fee_stracture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student_discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student_fees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(due_fees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parent_communities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        fifthsub_menuLayout.setVerticalGroup(
            fifthsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fifthsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(exp_type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fee_stracture, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(student_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(student_fees, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(due_fees, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parent_communities, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        sixthsub_menu.setBackground(new java.awt.Color(0, 39, 76));
        sixthsub_menu.setForeground(new java.awt.Color(255, 255, 255));
        sixthsub_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sixthsub_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton38.setBackground(new java.awt.Color(15, 108, 182));
        jButton38.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("DRIVER MASTER");
        jButton38.setBorder(null);

        jButton39.setBackground(new java.awt.Color(15, 108, 182));
        jButton39.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setText("ROUTE AND VECHILE");
        jButton39.setBorder(null);

        jButton41.setBackground(new java.awt.Color(15, 108, 182));
        jButton41.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("STUDENT VECHILE");
        jButton41.setBorder(null);

        javax.swing.GroupLayout sixthsub_menuLayout = new javax.swing.GroupLayout(sixthsub_menu);
        sixthsub_menu.setLayout(sixthsub_menuLayout);
        sixthsub_menuLayout.setHorizontalGroup(
            sixthsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sixthsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(sixthsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
        sixthsub_menuLayout.setVerticalGroup(
            sixthsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sixthsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        seventhsub_menu.setBackground(new java.awt.Color(0, 39, 76));
        seventhsub_menu.setForeground(new java.awt.Color(255, 255, 255));
        seventhsub_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        seventhsub_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton32.setBackground(new java.awt.Color(15, 108, 182));
        jButton32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("CATEOGRY AND ITEMS");
        jButton32.setBorder(null);

        jButton33.setBackground(new java.awt.Color(15, 108, 182));
        jButton33.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton33.setForeground(new java.awt.Color(255, 255, 255));
        jButton33.setText("INVENTORY AND SALES");
        jButton33.setBorder(null);

        jButton34.setBackground(new java.awt.Color(15, 108, 182));
        jButton34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("RETURN TO SUPPLIER");
        jButton34.setBorder(null);

        jButton35.setBackground(new java.awt.Color(15, 108, 182));
        jButton35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton35.setForeground(new java.awt.Color(255, 255, 255));
        jButton35.setText("RETURN ITEMS");
        jButton35.setBorder(null);

        javax.swing.GroupLayout seventhsub_menuLayout = new javax.swing.GroupLayout(seventhsub_menu);
        seventhsub_menu.setLayout(seventhsub_menuLayout);
        seventhsub_menuLayout.setHorizontalGroup(
            seventhsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seventhsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(seventhsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
        seventhsub_menuLayout.setVerticalGroup(
            seventhsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seventhsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        eightsub_menu.setBackground(new java.awt.Color(0, 51, 98));
        eightsub_menu.setForeground(new java.awt.Color(255, 255, 255));
        eightsub_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eightsub_menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton26.setBackground(new java.awt.Color(15, 108, 182));
        jButton26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("Academic Year");
        jButton26.setBorder(null);

        jButton27.setBackground(new java.awt.Color(15, 108, 182));
        jButton27.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("Users");
        jButton27.setBorder(null);

        jButton28.setBackground(new java.awt.Color(15, 108, 182));
        jButton28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("Standard Section");
        jButton28.setBorder(null);

        jButton29.setBackground(new java.awt.Color(15, 108, 182));
        jButton29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("Branch");
        jButton29.setBorder(null);

        jButton30.setBackground(new java.awt.Color(15, 108, 182));
        jButton30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("Restore Database");
        jButton30.setBorder(null);

        jButton31.setBackground(new java.awt.Color(15, 108, 182));
        jButton31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("Back Up Database");
        jButton31.setBorder(null);

        javax.swing.GroupLayout eightsub_menuLayout = new javax.swing.GroupLayout(eightsub_menu);
        eightsub_menu.setLayout(eightsub_menuLayout);
        eightsub_menuLayout.setHorizontalGroup(
            eightsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eightsub_menuLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(eightsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );
        eightsub_menuLayout.setVerticalGroup(
            eightsub_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eightsub_menuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
            .addComponent(mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(firstsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thirdsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fourthsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fifthsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sixthsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seventhsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eightsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fifthsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixthsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seventhsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightsub_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(desktopPane))
        );

        setSize(new java.awt.Dimension(1186, 757));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        if(maximizer){
            Home.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
//            Home.this.setMaximizedBounds(env.getMaximumWindowBounds());
            ii = new ImageIcon(getClass().getResource("/school/images/minimize.png"));
            maximize.setIcon(ii);
            maximizer = false;
        }else{
            setExtendedState(JFrame.NORMAL);
            ii = new ImageIcon(getClass().getResource("/school/images/maximize.png"));
            maximize.setIcon(ii);
            maximizer = true;
        }
    }//GEN-LAST:event_maximizeMouseClicked
 
    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void administratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administratorMouseEntered
        secondsub_menu.setSize(0,0);
        thirdsub_menu.setSize(0,0);
        fourthsub_menu.setSize(0,0);
        fifthsub_menu.setSize(0,0);
        sixthsub_menu.setSize(0,0);
        seventhsub_menu.setSize(0,0);
        eightsub_menu.setSize(0,0);
        firstsub_menu.setSize(166, 214);
        administrator.setBackground(new Color(15, 108, 182));
    }//GEN-LAST:event_administratorMouseEntered

    private void administratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administratorMouseExited
        //firstsub_menu.setSize(0,0);
        administrator.setBackground(new Color(0,39,76));
    }//GEN-LAST:event_administratorMouseExited

    private void studentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseEntered
        firstsub_menu.setSize(0,0);
        thirdsub_menu.setSize(0,0);
        fourthsub_menu.setSize(0,0);
        fifthsub_menu.setSize(0,0);
        sixthsub_menu.setSize(0,0);
        seventhsub_menu.setSize(0,0);
        eightsub_menu.setSize(0,0);
        secondsub_menu.setSize(166, 130);
        students.setBackground(new Color(15, 108, 182));
    }//GEN-LAST:event_studentsMouseEntered

    private void studentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsMouseExited
        // secondsub_menu.setSize(0,0);
        students.setBackground(new Color(0,39,76));
    }//GEN-LAST:event_studentsMouseExited

    private void attendenceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendenceMouseEntered
        firstsub_menu.setSize(0,0);
        secondsub_menu.setSize(0,0);
        fourthsub_menu.setSize(0,0);
        fifthsub_menu.setSize(0,0);
        sixthsub_menu.setSize(0,0);
        seventhsub_menu.setSize(0,0);
        eightsub_menu.setSize(0,0);
        thirdsub_menu.setSize(166, 96);
        attendence.setBackground(new Color(15, 108, 182));
    }//GEN-LAST:event_attendenceMouseEntered

    private void attendenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendenceMouseExited
        //thirdsub_menu.setSize(0,0);
        attendence.setBackground(new Color(0,39,76));
    }//GEN-LAST:event_attendenceMouseExited

    private void employessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employessMouseEntered
        firstsub_menu.setSize(0,0);
        secondsub_menu.setSize(0,0);
        thirdsub_menu.setSize(0,0);
        fifthsub_menu.setSize(0,0);
        sixthsub_menu.setSize(0,0);
        seventhsub_menu.setSize(0,0);
        eightsub_menu.setSize(0,0);
        fourthsub_menu.setSize(166, 50);
        employess.setBackground(new Color(15, 108, 182));
    }//GEN-LAST:event_employessMouseEntered

    private void employessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employessMouseExited
        // fourthsub_menu.setSize(0,0);
        employess.setBackground(new Color(0,39,76));
    }//GEN-LAST:event_employessMouseExited

    private void accountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseEntered
        firstsub_menu.setSize(0,0);
        secondsub_menu.setSize(0,0);
        thirdsub_menu.setSize(0,0);
        fourthsub_menu.setSize(0,0);
        sixthsub_menu.setSize(0,0);
        seventhsub_menu.setSize(0,0);
        eightsub_menu.setSize(0,0);
        fifthsub_menu.setSize(211, 256);
        accounts.setBackground(new Color(15, 108, 182));
    }//GEN-LAST:event_accountsMouseEntered

    private void accountsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseExited
        //fifthsub_menu.setSize(0,0);
        accounts.setBackground(new Color(0,39,76));
    }//GEN-LAST:event_accountsMouseExited

    private void transportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transportMouseEntered
        firstsub_menu.setSize(0,0);
        secondsub_menu.setSize(0,0);
        thirdsub_menu.setSize(0,0);
        fourthsub_menu.setSize(0,0);
        fifthsub_menu.setSize(0,0);
        seventhsub_menu.setSize(0,0);
        eightsub_menu.setSize(0,0);
        sixthsub_menu.setSize(166,130);
        transport.setBackground(new Color(15, 108, 182));
    }//GEN-LAST:event_transportMouseEntered

    private void transportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transportMouseExited
        // sixthsub_menu.setSize(0,0);
        transport.setBackground(new Color(0,39,76));
    }//GEN-LAST:event_transportMouseExited

    private void inventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseEntered
        firstsub_menu.setSize(0,0);
        secondsub_menu.setSize(0,0);
        thirdsub_menu.setSize(0,0);
        fourthsub_menu.setSize(0,0);
        fifthsub_menu.setSize(0,0);
        sixthsub_menu.setSize(0,0);
        eightsub_menu.setSize(0,0);
        seventhsub_menu.setSize(166,172);
        inventory.setBackground(new Color(15, 108, 182));
    }//GEN-LAST:event_inventoryMouseEntered

    private void inventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseExited
        //seventhsub_menu.setSize(0,0);
        inventory.setBackground(new Color(0,39,76));
    }//GEN-LAST:event_inventoryMouseExited

    private void reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseEntered
        firstsub_menu.setSize(0,0);
        secondsub_menu.setSize(0,0);
        thirdsub_menu.setSize(0,0);
        fourthsub_menu.setSize(0,0);
        fifthsub_menu.setSize(0,0);
        sixthsub_menu.setSize(0,0);
        seventhsub_menu.setSize(0,0);
    }//GEN-LAST:event_reportMouseEntered

    private void academic_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academic_yearActionPerformed

        /* AcademicYear academic = new AcademicYear();
        if(!academic.isVisible()){
        academic.setVisible(true);
        academic.pack();
        jDesktopPane.add(academic);
        Dimension desktopSize = jDesktopPane.getSize();
        Dimension jInternalFrameSize = academic.getSize();
        academic.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);
        try {
        academic.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
        }*/
        String x = AcademicYear.x;
        try {
            if (x == null) {
                AcademicYear academic = new AcademicYear();
                desktopPane.add(academic);
                desktopPane.moveToFront(academic);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Already Run Academic Year .");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }//GEN-LAST:event_academic_yearActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        String x = Users.x;
        try {
            if(x == null){
                Users user = new Users();
                desktopPane.add(user);
                desktopPane.moveToFront(user);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Already Run User .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_usersActionPerformed

    private void standard_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standard_sectionActionPerformed
        /*Branch.setVisible(true);
        Academic_Year.setVisible(false);
        Users.setVisible(false);
        Standard.setVisible(false);
        Database.setVisible(false);
        Registration.setVisible(false);
        BonafiedCertificate.setVisible(false);
        StudentPromotion.setVisible(false);
        student_attendance.setVisible(false);
        Employee_attendance.setVisible(false);
        Employee.setVisible(false);
        Expense_Type.setVisible(false);
        Fee_stracture.setVisible(false);
        Student_Discount.setVisible(false);
        Student_fees.setVisible(false);
        DueFees.setVisible(false);
        Parent_commitment.setVisible(false);
        Driver_Master.setVisible(false);
        Route_Vechile.setVisible(false);
        Student_Vechile.setVisible(false);
        Cateogry_item.setVisible(false);
        Inventory_Sales.setVisible(false);
        Return_Item.setVisible(false);
        Return_TO_SUPPLIER.setVisible(false);*/
        String x = Standard.x;
        try {
            if(x == null){
                Standard standard = new Standard();
                desktopPane.add(standard);
                desktopPane.moveToFront(standard);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Already Run Standard .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_standard_sectionActionPerformed

    private void branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchActionPerformed
        /*  Academic_Year.setVisible(false);
        Users.setVisible(false);
        Branch.setVisible(false);
        Standard.setVisible(false);
        Database.setVisible(false);
        Registration.setVisible(false);
        BonafiedCertificate.setVisible(false);
        StudentPromotion.setVisible(false);
        student_attendance.setVisible(false);
        Employee_attendance.setVisible(false);
        Employee.setVisible(false);
        Expense_Type.setVisible(false);
        Fee_stracture.setVisible(false);
        Student_Discount.setVisible(false);
        Student_fees.setVisible(false);
        DueFees.setVisible(false);
        Parent_commitment.setVisible(false);
        Driver_Master.setVisible(false);
        Route_Vechile.setVisible(false);
        Student_Vechile.setVisible(false);
        Cateogry_item.setVisible(false);
        Inventory_Sales.setVisible(false);
        Return_Item.setVisible(false);
        Return_TO_SUPPLIER.setVisible(false);*/
        String x = Branch.x;
        try {
            if(x == null){
                Branch branch = new Branch();
                desktopPane.add(branch);
                desktopPane.moveToFront(branch);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Already Run Branch .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_branchActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       firstsub_menu.setSize(0,0);
        secondsub_menu.setSize(0,0);
        thirdsub_menu.setSize(0,0);
        fourthsub_menu.setSize(0,0);
        fifthsub_menu.setSize(0,0);
        sixthsub_menu.setSize(0,0);
        seventhsub_menu.setSize(0,0);
        eightsub_menu.setSize(0,0);
    }//GEN-LAST:event_formMouseClicked

    private void backup_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backup_databaseActionPerformed
       String x = Database.x;
        try {
            if(x == null){
                Database database = new Database();
                desktopPane.add(database);
                desktopPane.moveToFront(database);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Already Run Database .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_backup_databaseActionPerformed

    private void RegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegButtonActionPerformed
         String x = Registration.x;
        try {
            if(x == null){
                Registration registration = new Registration();
                desktopPane.add(registration);
                desktopPane.moveToFront(registration);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Already Run Registration .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_RegButtonActionPerformed

    private void BonafiedCertiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BonafiedCertiActionPerformed
       String x = BonafiedCertificate.x;
        try {
            if(x == null){
                BonafiedCertificate bonafiedCertificate = new BonafiedCertificate();
                desktopPane.add(bonafiedCertificate);
                desktopPane.moveToFront(bonafiedCertificate);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Already Run BonafiedCertificate .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BonafiedCertiActionPerformed

    private void StudentPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPromoActionPerformed
        String x = StudentPromotion.x;
        try {
            if(x == null){
                StudentPromotion studentPromotion = new StudentPromotion();
                desktopPane.add(studentPromotion);
                desktopPane.moveToFront(studentPromotion);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Already Run BonafiedCertificate .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_StudentPromoActionPerformed

    private void student_attandanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_attandanceActionPerformed
        String x = StudentAttendance.x;
        try {
            if(x == null){
                StudentAttendance studentAttendance = new StudentAttendance();
                desktopPane.add(studentAttendance);
                desktopPane.moveToFront(studentAttendance);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "StudentAttendance Run User .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_student_attandanceActionPerformed

    private void employee_attandanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_attandanceActionPerformed
        String x = EmployeeAttendance.x;
        try {
            if(x == null){
                EmployeeAttendance employeeAttendance = new EmployeeAttendance();
                desktopPane.add(employeeAttendance);
                desktopPane.moveToFront(employeeAttendance);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "EmployeeAttendance Run User .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_employee_attandanceActionPerformed

    private void employee_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_registrationActionPerformed
         String x = EmployeeRegistration.x;
        try {
            if(x == null){
                EmployeeRegistration employeeRegistration = new EmployeeRegistration();
                desktopPane.add(employeeRegistration);
                desktopPane.moveToFront(employeeRegistration);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "EmployeeRegistration Run User .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_employee_registrationActionPerformed

    private void exp_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_typeActionPerformed
          String x = ExpensesType.x;
        try {
            if(x == null){
                ExpensesType expensesType = new ExpensesType();
                desktopPane.add(expensesType);
                desktopPane.moveToFront(expensesType);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "ExpensesType Running Please Close Tabs Then Open .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_exp_typeActionPerformed

    private void fee_stractureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fee_stractureActionPerformed
         String x = FeeStracture.x;
        try {
            if(x == null){
                FeeStracture feeStracture = new FeeStracture();
                desktopPane.add(feeStracture);
                desktopPane.moveToFront(feeStracture);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "FeeStracture Running Please Close Tabs Then Open .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_fee_stractureActionPerformed

    private void student_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_discountActionPerformed
         String x = StudentDiscount.x;
        try {
            if(x == null){
                StudentDiscount studentDiscount = new StudentDiscount();
                desktopPane.add(studentDiscount);
                desktopPane.moveToFront(studentDiscount);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "StudentDiscount Running Please Close Tabs Then Open .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_student_discountActionPerformed

    private void student_feesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_feesActionPerformed
         String x = StudentFees.x;
        try {
            if(x == null){
                StudentFees studentFees = new StudentFees();
                desktopPane.add(studentFees);
                desktopPane.moveToFront(studentFees);
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "StudentDiscount Running Please Close Tabs Then Open .");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_student_feesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BonafiedCerti;
    private javax.swing.JLabel Close;
    private javax.swing.JButton RegButton;
    private javax.swing.JButton StudentPromo;
    private javax.swing.JButton academic_year;
    private javax.swing.JButton accounts;
    private javax.swing.JButton administrator;
    private javax.swing.JButton attendence;
    private javax.swing.JButton backup_database;
    private javax.swing.JButton branch;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton due_fees;
    private javax.swing.JPanel eightsub_menu;
    private javax.swing.JButton employee_attandance;
    private javax.swing.JButton employee_registration;
    private javax.swing.JButton employess;
    private javax.swing.JButton exp_type;
    private javax.swing.JButton fee_stracture;
    private javax.swing.JPanel fifthsub_menu;
    private javax.swing.JPanel firstsub_menu;
    private javax.swing.JPanel fourthsub_menu;
    private javax.swing.JButton inventory;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton41;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainmenu;
    private javax.swing.JLabel maximize;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton parent_communities;
    private javax.swing.JButton report;
    private javax.swing.JPanel secondsub_menu;
    private javax.swing.JPanel seventhsub_menu;
    private javax.swing.JPanel sixthsub_menu;
    private javax.swing.JButton standard_section;
    private javax.swing.JButton student_attandance;
    private javax.swing.JButton student_discount;
    private javax.swing.JButton student_fees;
    private javax.swing.JButton students;
    private javax.swing.JPanel thirdsub_menu;
    private javax.swing.JButton transport;
    private javax.swing.JButton users;
    // End of variables declaration//GEN-END:variables
}
