/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashish Shahi
 */
public class StudentPromotion extends javax.swing.JInternalFrame {
         public static String x;
    /**
     * Creates new form JInternalFrame
     */
    public StudentPromotion() {
        initComponents();
         SelectStandard();
        x = "x";
        int a = Home.desktopPane.getWidth() - this.getWidth();
        int b = Home.desktopPane.getHeight() - this.getHeight();

        setLocation(a / 2, b / 2);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentPromotion = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        sectionsearch1 = new javax.swing.JButton();
        promo_section = new javax.swing.JComboBox<>();
        promo_standard = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("STUDENT PROMOTION");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/school/images/favicon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1186, 655));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        StudentPromotion.setPreferredSize(new java.awt.Dimension(1166, 583));

        jPanel18.setBackground(new java.awt.Color(35, 46, 64));
        jPanel18.setPreferredSize(new java.awt.Dimension(1139, 145));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Section :");

        sectionsearch1.setBackground(new java.awt.Color(0, 177, 176));
        sectionsearch1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sectionsearch1.setForeground(new java.awt.Color(255, 255, 255));
        sectionsearch1.setText("SEARCH STUDENTS");

        promo_section.setBackground(new java.awt.Color(35, 46, 64));
        promo_section.setForeground(new java.awt.Color(255, 255, 255));
        promo_section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        promo_section.setToolTipText("");
        promo_section.setBorder(null);

        promo_standard.setBackground(new java.awt.Color(35, 46, 64));
        promo_standard.setForeground(new java.awt.Color(255, 255, 255));
        promo_standard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        promo_standard.setToolTipText("");
        promo_standard.setBorder(null);
        promo_standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promo_standardActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Standard :");

        jLabel21.setBackground(new java.awt.Color(35, 46, 64));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(229, 83, 70));
        jLabel21.setText("*");

        jLabel22.setBackground(new java.awt.Color(35, 46, 64));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(229, 83, 70));
        jLabel22.setText("*");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(promo_standard, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(42, 42, 42)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(promo_section, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(20, 20, 20)
                .addComponent(sectionsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sectionsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(promo_section, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(promo_standard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel21))
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel22))))
                .addContainerGap(528, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StudentPromotionLayout = new javax.swing.GroupLayout(StudentPromotion);
        StudentPromotion.setLayout(StudentPromotionLayout);
        StudentPromotionLayout.setHorizontalGroup(
            StudentPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
        );
        StudentPromotionLayout.setVerticalGroup(
            StudentPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(StudentPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StudentPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
         x = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void promo_standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promo_standardActionPerformed
        promo_section.removeAllItems();
        String standard = promo_standard.getSelectedItem().toString();
        SelectSection(standard);
    }//GEN-LAST:event_promo_standardActionPerformed
  //Selecting Standard From Database
    public void SelectStandard(){
        try {
             Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
           Statement statement = con.createStatement();
           String selectedquery = "select standard from standard";
             ResultSet rs = statement.executeQuery(selectedquery);
             while(rs.next()){
                
                  promo_standard.addItem(rs.getString("standard")); 
                  /*stddrop.addItem(rs.getString("standard"));
                  standardname.addItem(rs.getString("standard"));
                  standard_name_search.addItem(rs.getString("standard"));
                  standard_student.addItem(rs.getString("standard"));
                  standard_attendance.addItem(rs.getString("standard"));
                  stnadard_student_search.addItem(rs.getString("standard"));*/
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //close to Select Standard
    //Start Select Section 
    public void SelectSection(String st){
        try {
             Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
           Statement statement = con.createStatement();
           String selectedquery = "select section from section where standard = '"+st+"' ";
             ResultSet rs = statement.executeQuery(selectedquery);
             while(rs.next()){
                 promo_section.addItem(rs.getString("section"));
                 /*sectionname.addItem(rs.getString("section"));
                 section_name_search.addItem(rs.getString("section"));
                 section_student.addItem(rs.getString("section"));
                 section_name_attendance.addItem(rs.getString("section"));
                 section_student_search.addItem(rs.getString("section"));*/
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentPromotion;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JComboBox<String> promo_section;
    private javax.swing.JComboBox<String> promo_standard;
    private javax.swing.JButton sectionsearch1;
    // End of variables declaration//GEN-END:variables
}
