/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.net.ConnectException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashish Shahi
 */
public class StudentDiscount extends javax.swing.JInternalFrame {
         public static String x;
    /**
     * Creates new form JInternalFrame
     */
    public StudentDiscount() {
        initComponents();
        SelectStandard();//selecting standard 
        SelectFeeOccuranceType();//selecting Fee Occurance Type
        x = "x";
        int a = Home.desktopPane.getWidth() - this.getWidth();
        int b = Home.desktopPane.getHeight() - this.getHeight();

        setLocation(a / 2, b / 2);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel32 = new javax.swing.JLabel();
        Student_discount = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        search_section = new javax.swing.JComboBox<>();
        search_standard = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        search_studentname = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        search_enrollment_no = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        standard = new javax.swing.JComboBox<>();
        section = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        studentname = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        enrollmanr_no = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        fee_occurance = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        fee_cateogry = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        application_form = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        total_amount = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        total_discount = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        amount_after_discount = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        add = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        jLabel32.setBackground(new java.awt.Color(35, 46, 64));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(229, 83, 70));
        jLabel32.setText("*");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("STUDENT DISCOUNT");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/school/images/favicon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1186, 655));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Student_discount.setPreferredSize(new java.awt.Dimension(1166, 583));

        jTabbedPane4.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane4.setForeground(new java.awt.Color(0, 39, 76));
        jTabbedPane4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTabbedPane4.setPreferredSize(new java.awt.Dimension(1146, 201));

        jPanel7.setBackground(new java.awt.Color(35, 46, 64));
        jPanel7.setPreferredSize(new java.awt.Dimension(1139, 145));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STANDARD :");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SECTION NAME :");

        search.setBackground(new java.awt.Color(0, 177, 176));
        search.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");

        search_section.setBackground(new java.awt.Color(35, 46, 64));
        search_section.setForeground(new java.awt.Color(255, 255, 255));
        search_section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        search_section.setToolTipText("");
        search_section.setBorder(null);
        search_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_sectionActionPerformed(evt);
            }
        });

        search_standard.setBackground(new java.awt.Color(35, 46, 64));
        search_standard.setForeground(new java.awt.Color(255, 255, 255));
        search_standard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        search_standard.setToolTipText("");
        search_standard.setBorder(null);
        search_standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_standardActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("STUDENT NAME :");

        search_studentname.setBackground(new java.awt.Color(35, 46, 64));
        search_studentname.setForeground(new java.awt.Color(255, 255, 255));
        search_studentname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        search_studentname.setToolTipText("");
        search_studentname.setBorder(null);
        search_studentname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_studentnameMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ENROLLMENT NO :");

        search_enrollment_no.setEditable(false);
        search_enrollment_no.setBackground(new java.awt.Color(35, 46, 64));
        search_enrollment_no.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        search_enrollment_no.setForeground(new java.awt.Color(255, 255, 255));
        search_enrollment_no.setBorder(null);
        search_enrollment_no.setCaretColor(new java.awt.Color(255, 255, 255));
        search_enrollment_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_enrollment_noMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(search_standard, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(search_studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator7)
                    .addComponent(search_enrollment_no, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(search_section, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_standard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_section, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_enrollment_no, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search_studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(477, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("SEARCH", jPanel7);

        jPanel8.setBackground(new java.awt.Color(35, 46, 64));
        jPanel8.setPreferredSize(new java.awt.Dimension(1139, 145));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("SECTION  :");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("STANDARD :");

        clear.setBackground(new java.awt.Color(0, 177, 176));
        clear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        standard.setBackground(new java.awt.Color(35, 46, 64));
        standard.setForeground(new java.awt.Color(255, 255, 255));
        standard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        standard.setToolTipText("");
        standard.setBorder(null);
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        section.setBackground(new java.awt.Color(35, 46, 64));
        section.setForeground(new java.awt.Color(255, 255, 255));
        section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        section.setToolTipText("");
        section.setBorder(null);
        section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("STUDENT NAME :");

        studentname.setBackground(new java.awt.Color(35, 46, 64));
        studentname.setForeground(new java.awt.Color(255, 255, 255));
        studentname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        studentname.setToolTipText("");
        studentname.setBorder(null);
        studentname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentnameMouseClicked(evt);
            }
        });
        studentname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnameActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ENROLLMENT NO :");

        enrollmanr_no.setBackground(new java.awt.Color(35, 46, 64));
        enrollmanr_no.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enrollmanr_no.setForeground(new java.awt.Color(255, 255, 255));
        enrollmanr_no.setBorder(null);
        enrollmanr_no.setCaretColor(new java.awt.Color(255, 255, 255));

        fee_occurance.setBackground(new java.awt.Color(35, 46, 64));
        fee_occurance.setForeground(new java.awt.Color(255, 255, 255));
        fee_occurance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        fee_occurance.setToolTipText("");
        fee_occurance.setBorder(null);
        fee_occurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fee_occuranceActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("FEE CATEOGRY :");

        fee_cateogry.setBackground(new java.awt.Color(35, 46, 64));
        fee_cateogry.setForeground(new java.awt.Color(255, 255, 255));
        fee_cateogry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        fee_cateogry.setToolTipText("");
        fee_cateogry.setBorder(null);
        fee_cateogry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fee_cateogryActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("FEE OCCURENCE  :");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("APPLICABLE FROM :");

        application_form.setBackground(new java.awt.Color(35, 46, 64));
        application_form.setForeground(new java.awt.Color(255, 255, 255));
        application_form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        application_form.setToolTipText("");
        application_form.setBorder(null);
        application_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                application_formActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("TOTAL AMOUNT  :");

        total_amount.setEditable(false);
        total_amount.setBackground(new java.awt.Color(35, 46, 64));
        total_amount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        total_amount.setForeground(new java.awt.Color(255, 255, 255));
        total_amount.setBorder(null);
        total_amount.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("TOTAL DISCOUNT  :");

        total_discount.setBackground(new java.awt.Color(35, 46, 64));
        total_discount.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        total_discount.setForeground(new java.awt.Color(255, 255, 255));
        total_discount.setBorder(null);
        total_discount.setCaretColor(new java.awt.Color(255, 255, 255));
        total_discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                total_discountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                total_discountKeyReleased(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("AMOUNT AFTER DISCOUNT  :");

        amount_after_discount.setEditable(false);
        amount_after_discount.setBackground(new java.awt.Color(35, 46, 64));
        amount_after_discount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        amount_after_discount.setForeground(new java.awt.Color(204, 0, 51));
        amount_after_discount.setBorder(null);
        amount_after_discount.setCaretColor(new java.awt.Color(255, 255, 255));
        amount_after_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_after_discountActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(0, 177, 176));
        add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(35, 46, 64));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(229, 83, 70));
        jLabel14.setText("*");

        jLabel15.setBackground(new java.awt.Color(35, 46, 64));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(229, 83, 70));
        jLabel15.setText("*");

        jLabel16.setBackground(new java.awt.Color(35, 46, 64));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(229, 83, 70));
        jLabel16.setText("*");

        jLabel17.setBackground(new java.awt.Color(35, 46, 64));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(229, 83, 70));
        jLabel17.setText("*");

        jLabel18.setBackground(new java.awt.Color(35, 46, 64));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(229, 83, 70));
        jLabel18.setText("*");

        jLabel31.setBackground(new java.awt.Color(35, 46, 64));
        jLabel31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(229, 83, 70));
        jLabel31.setText("*");

        jLabel33.setBackground(new java.awt.Color(35, 46, 64));
        jLabel33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(229, 83, 70));
        jLabel33.setText("*");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(enrollmanr_no, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(application_form, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(section, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fee_occurance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(standard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fee_cateogry, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(total_amount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(amount_after_discount, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel31))
                .addGap(233, 233, 233))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fee_occurance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(application_form, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(total_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(standard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(enrollmanr_no, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fee_cateogry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(amount_after_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33))))))
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("ADD", jPanel8);

        javax.swing.GroupLayout Student_discountLayout = new javax.swing.GroupLayout(Student_discount);
        Student_discount.setLayout(Student_discountLayout);
        Student_discountLayout.setHorizontalGroup(
            Student_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(Student_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, Short.MAX_VALUE))
        );
        Student_discountLayout.setVerticalGroup(
            Student_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
            .addGroup(Student_discountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Student_discountLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Student_discount, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Student_discount, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
         x = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void search_standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_standardActionPerformed
        search_section.removeAllItems();
        String standard = search_standard.getSelectedItem().toString();
        SelectSection(standard);
         //search_studentname.removeAllItems();
        //String standard = search_standard.getSelectedItem().toString();
        //String sections = search_section.getSelectedItem().toString();
        //SelectStudent(standard, sections/*"A"*/);
    }//GEN-LAST:event_search_standardActionPerformed

    private void sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionActionPerformed
         studentname.removeAllItems();
        studentname.addItem("Select Student Name");
    }//GEN-LAST:event_sectionActionPerformed

    private void studentnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnameActionPerformed

    private void fee_occuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fee_occuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fee_occuranceActionPerformed

    private void fee_cateogryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fee_cateogryActionPerformed
        total_amount.setText("0.000");
        String FeeOccurance = fee_occurance.getSelectedItem().toString();
        String FeeCateogry = fee_cateogry.getSelectedItem().toString();
        CalculateAmount(FeeOccurance,FeeCateogry);
    }//GEN-LAST:event_fee_cateogryActionPerformed

    private void application_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_application_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_application_formActionPerformed

    private void amount_after_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_after_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount_after_discountActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
        section.removeAllItems();
        search_enrollment_no.setText("");
        String standards = standard.getSelectedItem().toString();
        SelectSection(standards);
    }//GEN-LAST:event_standardActionPerformed

    private void search_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_sectionActionPerformed
        search_studentname.removeAllItems();
        search_studentname.addItem("Select Student Name");
        /*String standard = search_standard.getSelectedItem().toString();
        String sections = search_section.getSelectedItem().toString();
        SelectStudent(standard, sections"A");*/
        /*search_studentname.removeAllItems();
        String standard = search_standard.getSelectedItem().toString();
        String sections = search_section.getSelectedItem().toString();
        SelectStudent(standard, sections"A");
        //SelectStudent("ashish", "kumar");*/
    }//GEN-LAST:event_search_sectionActionPerformed

    private void search_studentnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_studentnameMouseClicked
        search_studentname.removeAllItems();
        search_enrollment_no.setText("Click Here For View Enrollment No");
        String standard = search_standard.getSelectedItem().toString();
        String sections = search_section.getSelectedItem().toString();
        SelectStudent(standard, sections);
    }//GEN-LAST:event_search_studentnameMouseClicked

    private void search_enrollment_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_enrollment_noMouseClicked
         search_enrollment_no.setText("");
        String standard = search_standard.getSelectedItem().toString();
        String sections = search_section.getSelectedItem().toString();
        String name = search_studentname.getSelectedItem().toString();
        SelectStudent(standard, sections);
        GettingEnrollment(standard, sections, name);
    }//GEN-LAST:event_search_enrollment_noMouseClicked

    private void studentnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentnameMouseClicked
        studentname.removeAllItems();
        String standards = standard.getSelectedItem().toString();
        String sections = section.getSelectedItem().toString();
        SelectStudent(standards, sections);
    }//GEN-LAST:event_studentnameMouseClicked

    private void total_discountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_discountKeyPressed
        /* int amount = Integer.parseInt(total_amount.getText());
        int discount = Integer.parseInt(total_discount.getText());
        String result = Integer.toString(amount - discount);
        amount_after_discount.setText(result);*/
//        try {
//           if(total_discount.getText() != null){
//                int amount = Integer.parseInt(total_amount.getText());
//                int discount = Integer.parseInt(total_discount.getText());
//                String result = Integer.toString(amount - discount);
//                amount_after_discount.setText(result/*Integer.toString(Integer.parseInt(total_amount.getText()) - Integer.parseInt(total_discount.getText()))*/);
//        } 
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_total_discountKeyPressed

    private void total_discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_discountKeyReleased
        int discount = 0; 
        try { 
        int amount = Integer.parseInt(total_amount.getText());
        String result;
        if(total_discount.getText() != null){ 
            discount = Integer.parseInt(total_discount.getText());
             result = Integer.toString(amount - discount);
           }else{
                discount = 0; 
                 result = Integer.toString(amount - discount);
            }
               amount_after_discount.setText(result);
        } catch (Exception e) {
           
            JOptionPane.showMessageDialog(null, "Please Enter Discount Amount");
            total_discount.setText("0");
        }
        
               
    }//GEN-LAST:event_total_discountKeyReleased

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
            if(con != null){
                System.out.println("Connection Sucessfully");
            }
            String sql = "Insert Into discount (enrollment_no, standard, `Section`, `name`, fee_occurance, fee_cateogry, applicable_from, amount, discount, final_amount) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,enrollmanr_no.getText().trim());
            pst.setString(2,standard.getSelectedItem().toString());
            pst.setString(3, section.getSelectedItem().toString());
            pst.setString(4, studentname.getSelectedItem().toString());
            pst.setString(5, fee_occurance.getSelectedItem().toString());
            pst.setString(6, fee_cateogry.getSelectedItem().toString());
            pst.setString(7, application_form.getSelectedItem().toString());
            pst.setString(8, total_amount.getText().trim());
            pst.setString(9, total_discount.getText().trim());
            pst.setString(10, amount_after_discount.getText().trim());
            int rowsInserted = pst.executeUpdate();
            if(rowsInserted>0){
                JOptionPane.showMessageDialog(null, "Sucessfully Added Student Discount.");
                clear();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clear();
    }//GEN-LAST:event_clearActionPerformed
//clear student discount item
    public void clear(){
        enrollmanr_no.setText("");
        standard.setSelectedIndex(0);
        section.setSelectedIndex(0);
        studentname.setSelectedIndex(0);
        fee_occurance.setSelectedIndex(0);
        fee_cateogry.setSelectedIndex(0);
        application_form.setSelectedIndex(0);
        total_amount.setText("");
        total_discount.setText("");
        amount_after_discount.setText("");
    }
//Selecting Standard From Database
    public void SelectStandard(){
        try {
             Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
           Statement statement = con.createStatement();
           String selectedquery = "select standard from standard";
             ResultSet rs = statement.executeQuery(selectedquery);
             while(rs.next()){
                 search_standard.addItem(rs.getString("standard"));
                 standard.addItem(rs.getString("standard"));
                
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //close to Select Standard
    //Start Select Section 
    public void SelectSection(String st){
        try {
             Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
           Statement statement = con.createStatement();
           String selectedquery = "select section from section where standard = '"+st+"' ";
             ResultSet rs = statement.executeQuery(selectedquery);
             while(rs.next()){
                 section.addItem(rs.getString("section"));
                 search_section.addItem(rs.getString("section"));
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //Start selecting Students.
    public void SelectStudent(String Standard ,String Section ){
        try {
            Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
            Statement statement = con.createStatement();
            String selectedquery = "select name from students where standard = '"+Standard+"' AND section = '"+Section+"' ORDER By name ASC";
//            String selectedquery ="select * from students where standard = '1st' OR section = 'A' ORDER By name ASC";
            ResultSet rs = statement.executeQuery(selectedquery);
            while(rs.next()){
                studentname.addItem(rs.getString("name"));
                search_studentname.addItem(rs.getString("name"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void GettingEnrollment(String Standard,String Section ,String Name)
    {
        try {
            Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
            Statement statement = con.createStatement();
            String selectedquery = "select enrollment_no from students where standard = '"+Standard+"' AND section = '"+Section+"' AND name = '"+Name+"'";
            ResultSet rs = statement.executeQuery(selectedquery);
            while(rs.next()){
                search_enrollment_no.setText(rs.getString("enrollment_no"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //feeoccuramce and select cateogry of fee type                                      
      //Selecting Expenses Type From Database
    public void SelectFeeOccuranceType(){
        try {
             Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
           Statement statement = con.createStatement();
           String selectedquery = "select * from FeeOccurance";
             ResultSet rs = statement.executeQuery(selectedquery);
             while(rs.next()){
                 fee_occurance.addItem(rs.getString("fee_occurance"));
                 application_form.addItem(rs.getString("fee_occurance"));
                 fee_cateogry.addItem(rs.getString("fee_cateogry_name"));
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //calculating total amount 
    public void CalculateAmount(String fee_occurance,String fee_cateogry){
        try {
            Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
            Statement statement = con.createStatement();
            String selectedquery = "Select * from feesetup where fee_occurance = '"+fee_occurance+"' And fee_cateogry = '"+fee_cateogry+"'";
            ResultSet rs = statement.executeQuery(selectedquery);
            while(rs.next()){
                total_amount.setText(rs.getString("fee_amount"));
            }
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Student_discount;
    private javax.swing.JButton add;
    private javax.swing.JTextField amount_after_discount;
    private javax.swing.JComboBox<String> application_form;
    private javax.swing.JButton clear;
    private javax.swing.JTextField enrollmanr_no;
    private javax.swing.JComboBox<String> fee_cateogry;
    private javax.swing.JComboBox<String> fee_occurance;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_enrollment_no;
    private javax.swing.JComboBox<String> search_section;
    private javax.swing.JComboBox<String> search_standard;
    private javax.swing.JComboBox<String> search_studentname;
    private javax.swing.JComboBox<String> section;
    private javax.swing.JComboBox<String> standard;
    private javax.swing.JComboBox<String> studentname;
    private javax.swing.JTextField total_amount;
    private javax.swing.JTextField total_discount;
    // End of variables declaration//GEN-END:variables
}
