/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashish Shahi
 */
public class StudentAttendance extends javax.swing.JInternalFrame {
         public static String x;
    /**
     * Creates new form JInternalFrame
     */
    public StudentAttendance() {
        initComponents();
        SelectStandard();//set standard in a drop down 
        setdate(date_of_attendance);//setting Today Date
        setdate(to_date);//setting Today Date
        x = "x";
        int a = Home.desktopPane.getWidth() - this.getWidth();
        int b = Home.desktopPane.getHeight() - this.getHeight();

        setLocation(a / 2, b / 2);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_attendance = new javax.swing.JPanel();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel22 = new javax.swing.JPanel();
        stnadard_student_search = new javax.swing.JComboBox<>();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        to_date = new com.toedter.calendar.JDateChooser();
        jLabel55 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        search_button5 = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        from_date = new com.toedter.calendar.JDateChooser();
        section_student_search = new javax.swing.JComboBox<>();
        jPanel21 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        search_button4 = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        date_of_attendance = new com.toedter.calendar.JDateChooser();
        section_name_attendance = new javax.swing.JComboBox<>();
        standard_attendance = new javax.swing.JComboBox<>();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        student_attendaence_sheet = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("STUDENT ATTENDANCE");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/school/images/favicon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1186, 655));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        student_attendance.setPreferredSize(new java.awt.Dimension(1166, 583));

        jTabbedPane9.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 106, 85), 2, true), "STUDENT ATTENDANCE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 39, 76))); // NOI18N
        jTabbedPane9.setForeground(new java.awt.Color(0, 39, 76));
        jTabbedPane9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTabbedPane9.setPreferredSize(new java.awt.Dimension(1146, 201));

        jPanel22.setBackground(new java.awt.Color(35, 46, 64));
        jPanel22.setPreferredSize(new java.awt.Dimension(1139, 145));

        stnadard_student_search.setBackground(new java.awt.Color(35, 46, 64));
        stnadard_student_search.setForeground(new java.awt.Color(255, 255, 255));
        stnadard_student_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        stnadard_student_search.setToolTipText("");
        stnadard_student_search.setBorder(null);
        stnadard_student_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnadard_student_searchActionPerformed(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("STANDARD :");

        jLabel74.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("To Date :");

        jLabel55.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("From Date :");

        jLabel75.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("SECTION  :");

        jLabel76.setBackground(new java.awt.Color(35, 46, 64));
        jLabel76.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(229, 83, 70));
        jLabel76.setText("*");

        search_button5.setBackground(new java.awt.Color(0, 177, 176));
        search_button5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        search_button5.setForeground(new java.awt.Color(255, 255, 255));
        search_button5.setText("SEARCH");
        search_button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_button5ActionPerformed(evt);
            }
        });

        jLabel77.setBackground(new java.awt.Color(35, 46, 64));
        jLabel77.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(229, 83, 70));
        jLabel77.setText("*");

        section_student_search.setBackground(new java.awt.Color(35, 46, 64));
        section_student_search.setForeground(new java.awt.Color(255, 255, 255));
        section_student_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        section_student_search.setToolTipText("");
        section_student_search.setBorder(null);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(from_date, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stnadard_student_search, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel77)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(to_date, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(section_student_search, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel76)
                        .addGap(54, 54, 54)
                        .addComponent(search_button5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(341, 341, 341))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(from_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(to_date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(section_student_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel76)
                                .addComponent(search_button5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(stnadard_student_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel22Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel77))))
                        .addGap(8, 8, 8)))
                .addContainerGap(475, Short.MAX_VALUE))
        );

        jTabbedPane9.addTab("SEARCH", jPanel22);

        jPanel21.setBackground(new java.awt.Color(35, 46, 64));
        jPanel21.setPreferredSize(new java.awt.Dimension(1139, 145));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Attendance Date :");

        jLabel69.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("SECTION  :");

        jLabel70.setBackground(new java.awt.Color(35, 46, 64));
        jLabel70.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(229, 83, 70));
        jLabel70.setText("*");

        search_button4.setBackground(new java.awt.Color(0, 177, 176));
        search_button4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        search_button4.setForeground(new java.awt.Color(255, 255, 255));
        search_button4.setText("SEARCH");
        search_button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_button4ActionPerformed(evt);
            }
        });

        jLabel71.setBackground(new java.awt.Color(35, 46, 64));
        jLabel71.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(229, 83, 70));
        jLabel71.setText("*");

        date_of_attendance.setBackground(new java.awt.Color(35, 46, 64));
        date_of_attendance.setForeground(new java.awt.Color(255, 255, 255));

        section_name_attendance.setBackground(new java.awt.Color(35, 46, 64));
        section_name_attendance.setForeground(new java.awt.Color(255, 255, 255));
        section_name_attendance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        section_name_attendance.setToolTipText("");
        section_name_attendance.setBorder(null);

        standard_attendance.setBackground(new java.awt.Color(35, 46, 64));
        standard_attendance.setForeground(new java.awt.Color(255, 255, 255));
        standard_attendance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        standard_attendance.setToolTipText("");
        standard_attendance.setBorder(null);
        standard_attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standard_attendanceActionPerformed(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("STANDARD :");

        student_attendaence_sheet.setBackground(new java.awt.Color(35, 46, 64));
        student_attendaence_sheet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(183, 209, 238), 2, true));
        student_attendaence_sheet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        student_attendaence_sheet.setForeground(new java.awt.Color(255, 255, 255));
        student_attendaence_sheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enroll-No", "Student", "Standard", "Section", "Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_attendaence_sheet.setGridColor(new java.awt.Color(255, 255, 255));
        student_attendaence_sheet.setRowHeight(40);
        student_attendaence_sheet.setRowMargin(5);
        student_attendaence_sheet.setSelectionBackground(new java.awt.Color(0, 177, 176));
        jScrollPane1.setViewportView(student_attendaence_sheet);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_of_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(standard_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel71)
                .addGap(18, 18, 18)
                .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(section_name_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel70)
                .addGap(50, 50, 50)
                .addComponent(search_button4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jScrollPane1)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_of_attendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(standard_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_button4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71)))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel70))
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(section_name_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane9.addTab("ADD", jPanel21);

        javax.swing.GroupLayout student_attendanceLayout = new javax.swing.GroupLayout(student_attendance);
        student_attendance.setLayout(student_attendanceLayout);
        student_attendanceLayout.setHorizontalGroup(
            student_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1166, Short.MAX_VALUE)
        );
        student_attendanceLayout.setVerticalGroup(
            student_attendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(student_attendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(student_attendance, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
         x = null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void stnadard_student_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnadard_student_searchActionPerformed
        section_student_search.removeAllItems();
        String standard = stnadard_student_search.getSelectedItem().toString();
        SelectSection(standard);
    }//GEN-LAST:event_stnadard_student_searchActionPerformed

    private void search_button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_button5ActionPerformed

    private void search_button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_button4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) student_attendaence_sheet.getModel();
        model.setRowCount(0);
        showuser();

    }//GEN-LAST:event_search_button4ActionPerformed

    private void standard_attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standard_attendanceActionPerformed
        section_name_attendance.removeAllItems();
        String standard = standard_attendance.getSelectedItem().toString();
        SelectSection(standard);
    }//GEN-LAST:event_standard_attendanceActionPerformed
     //setting Table date
      public ArrayList<user> userList(){
        ArrayList<user> userList = new ArrayList<>();
        try {
            Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
            Statement statement = con.createStatement(); 
            String sql = "select * from students where standard = '"+standard_attendance.getSelectedItem()+"' AND section = '"+section_name_attendance.getSelectedItem()+"' order by enrollment_no ASC ";
            ResultSet rs = statement.executeQuery(sql);
            user us;
            while(rs.next())
            {
                us = new user(rs.getString("enrollment_no"),rs.getString("name"),rs.getString("standard"),rs.getString("section")/*,rs.getString("time"),rs.getString("status")*/);
                userList.add(us);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return userList;
    } 
    public void showuser(){
        ArrayList<user> list = userList();
        DefaultTableModel model = (DefaultTableModel)student_attendaence_sheet.getModel();
        Object[] row = new Object[6];
        for(int i = 0; i<list.size();i++){
            row[0] = list.get(i).getenroll_no();
            row[1] = list.get(i).getstudent();
            row[2] = list.get(i).getstandard();
            row[3] = list.get(i).getsection();
            row[4] = list.get(i).gettime();
            row[5] = list.get(i).status();
            model.addRow(row);
        }
       
    } 
     
    //Selecting Standard From Database
    public void SelectStandard(){
        try {
             Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
           Statement statement = con.createStatement();
           String selectedquery = "select standard from standard";
             ResultSet rs = statement.executeQuery(selectedquery);
             while(rs.next()){
                 /* stddrop.addItem(rs.getString("standard"));
                 standardname.addItem(rs.getString("standard"));
                 promo_standard.addItem(rs.getString("standard"));
                 standard_name_search.addItem(rs.getString("standard"));
                 standard_student.addItem(rs.getString("standard"));*/
                 standard_attendance.addItem(rs.getString("standard"));
                 stnadard_student_search.addItem(rs.getString("standard"));
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //close to Select Standard
    //Start Select Section 
    public void SelectSection(String st){
        try {
             Connection con = (Connection) DriverManager.getConnection(Config.DbUrl,Config.DbUser,Config.DbPass);
           Statement statement = con.createStatement();
           String selectedquery = "select section from section where standard = '"+st+"' ";
             ResultSet rs = statement.executeQuery(selectedquery);
             while(rs.next()){
                 /* sectionname.addItem(rs.getString("section"));
                 promo_section.addItem(rs.getString("section"));
                 section_name_search.addItem(rs.getString("section"));
                 section_student.addItem(rs.getString("section"));*/
                 section_name_attendance.addItem(rs.getString("section"));
                 section_student_search.addItem(rs.getString("section"));
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     //fuction for setting Today Date In Today Date Pickers
    public void setdate(JDateChooser chooser){
    java.util.Date date = new java.util.Date();
    chooser.setDate(date);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date_of_attendance;
    private com.toedter.calendar.JDateChooser from_date;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JButton search_button4;
    private javax.swing.JButton search_button5;
    private javax.swing.JComboBox<String> section_name_attendance;
    private javax.swing.JComboBox<String> section_student_search;
    private javax.swing.JComboBox<String> standard_attendance;
    private javax.swing.JComboBox<String> stnadard_student_search;
    private javax.swing.JTable student_attendaence_sheet;
    private javax.swing.JPanel student_attendance;
    private com.toedter.calendar.JDateChooser to_date;
    // End of variables declaration//GEN-END:variables
}
